-- MYSQL
create DATABASE IF NOT exists AD5;
USE AD5;
create table ´CENTROS´ (
´NUMCE´ INT(4) NOT NULL,
´NOMCE´ varchar(25),
´DIRCE´ varchar(25)
);
CREATE TABLE ´DEPARTAMENTOS´ (
´NUMDE´ INT(3) NOT NULL,
´NUMCE´ INT(4),
´DIREC´ INT(3),
´TIDIR´ CHAR(1),
´PRESU´ numeric (3,1),
´DEPDE´ INT(3),
´NOMDE´ VARCHAR(20)
);
CREATE TABLE ´EMPLEADOS´ (
´NUMEM´ INT(3) NOT NULL,
´EXTEL´ INT(3),
´FECNA´ DATE ,
´FECIN´ DATE,
´SALAR´ INT(5),
´COMIS´ INT(3),
´NUMHI´ INT(1),
´NOMEM´ VARCHAR (10),
´NUMDE´ INT(3)
);

-- Primary key de todas las tablas
ALTER TABLE ´CENTROS´
ADD PRIMARY KEY (´NUMCE´);

ALTER TABLE ´DEPARTAMENTOS´
ADD PRIMARY KEY (´NUMDE´);

ALTER TABLE ´EMPLEADOS´
ADD PRIMARY KEY (´NUMEM´);

-- Foreign key que hayan en las tablas
ALTER TABLE ´DEPARTAMENTOS´
ADD CONSTRAINT Empleados_Departamentos_FK
FOREIGN KEY (´NUMCE´) REFERENCES ´CENTROS´ (´NUMCE´);
        
ALTER TABLE ´DEPARTAMENTOS´
ADD CONSTRAINT Departamentos_FK
FOREIGN KEY (´DEPDE´) REFERENCES ´DEPARTAMENTOS´ (´NUMDE´);

ALTER TABLE ´EMPLEADOS´
ADD CONSTRAINT Departamentos_EmpleadosFK
FOREIGN KEY (´NUMDE´) REFERENCES ´DEPARTAMENTOS´ (´NUMDE´);

-- Introducimos datos en la tabla DEPARTAMENTOS
INSERT INTO ´DEPARTAMENTOS´ (´NUMDE´,´NUMCE´,´DIREC´,´TIDIR´,´PRESU´,´DEPDE´,´NOMDE´) VALUES
(100,10,260,'P',72,null,'DIRECCION GENERAL'),
(110,20,180,'P',90,100,'DIRECCION COMERCIAL'),
(111,20,180,'F',66,110,'SECTOR INDUSTRIAL'),
(112,20,270,'P',54,110,'SECTOR SERVICIOS'),
(120,10,150,'F',18,100,'ORGANIZACIÓN'),
(121,10,150,'P',12,120,'PERSONAL'),
(122,10,350,'P',36,120,'PROCESO DE DATOS'),
(130,10,310,'P',12,100,'FINANZAS');
-- ME DA ERROR 1452. Cannot add or update a child row: a foreign key constraint fails"

-- Introducimos datos en la tabla CENTROS
INSERT INTO ´CENTROS´ (´NUMCE´,´NOMCE´,´DIRCE´)VALUES
(10,'SEDE CENTRAL','C/ATOCHA ,820,MADRID'),
(20,'RELACION CON CLIENTES','C/ATOCHA,405,MADRID');






